// Sample + random email data for the Test Replyloop page (ported from app.html).

export interface SampleEmail {
  name: string;
  email: string;
  subject: string;
  body: string;
}

export const SAMPLES: Record<string, SampleEmail> = {
  refund: { name: "Sarah Johnson", email: "sarah@example.com", subject: "I want to return my order", body: "Hi, I bought a jacket from your store last week but it doesn't fit. I'd like to return it and get a refund. Can you help me with this? Order #12345." },
  shipping: { name: "Mike Chen", email: "mike@gmail.com", subject: "Where is my package?", body: "I placed an order 8 days ago (order #67890) and I still haven't received anything. The tracking number you sent isn't showing any updates. I need this for an event this weekend, please help!" },
  password: { name: "Emma Davis", email: "emma@company.com", subject: "Cannot log into my account", body: "Hello, I've been trying to log into my account for the past hour and it keeps saying my password is wrong. I've tried resetting it but I'm not receiving the email. Please help, I need access urgently." },
  complaint: { name: "Robert Wilson", email: "rwilson@email.com", subject: "Terrible experience - very disappointed", body: "I am absolutely furious with your service. This is the third time my order has been wrong, and nobody seems to care. Your customer service is completely useless. I want someone to call me immediately or I am going to leave very negative reviews everywhere." },
};

export const RANDOM_POOL: SampleEmail[] = [
  { name: "Lucas Martin", email: "lucas.martin@gmail.com", subject: "I need a refund urgently", body: "Hello, I placed an order 3 days ago (order #44521) and I want to cancel it immediately. The product I ordered was a birthday gift but the birthday already passed. Please refund me as soon as possible." },
  { name: "Amelia Thompson", email: "amelia.t@hotmail.com", subject: "Wrong item received", body: "Hi there, I received my order today but it was completely wrong. I ordered a blue shirt in size M but received a red one in size XL. I need the correct item or a full refund. This is really disappointing." },
  { name: "Noah Williams", email: "noah.w@yahoo.com", subject: "Return request - damaged product", body: "I received a damaged product in my last order. The screen of the phone case is cracked and the packaging was completely destroyed. I would like to return this and get a replacement or refund. Order number is #78932." },
  { name: "Isabella Garcia", email: "isabella.garcia@outlook.com", subject: "My order is very late", body: "Good morning, I ordered a dress for my sister's wedding which is in 3 days and I still haven't received my order. It's been 12 days since I placed the order. This is very stressful, please help!" },
  { name: "Ethan Brown", email: "ethan.brown@gmail.com", subject: "Tracking not working", body: "Hi, I've been trying to track my package for the past week but the tracking page keeps showing \"no information available\". Can you tell me where my package is? Order #55123 placed on the 1st." },
  { name: "Mia Johnson", email: "mia.j@icloud.com", subject: "Delivery to wrong address?", body: "Hello, I think my package might have been delivered to the wrong address. The tracking says delivered but I haven't received anything. My neighbor hasn't seen it either. Can you please investigate? Order #33456." },
  { name: "Oliver Davis", email: "oliver.davis@gmail.com", subject: "Locked out of my account", body: "Hi, I've been locked out of my account for two days now. I tried resetting my password but I'm not receiving any emails. I've checked my spam folder too. I really need access to track my orders." },
  { name: "Sophia Martinez", email: "sophia.m@gmail.com", subject: "Account hacked I think", body: "I just noticed some strange activity on my account. There are orders I didn't place. I think my account has been hacked. Please help me secure my account immediately and cancel any unauthorized orders." },
  { name: "James Anderson", email: "james.a@work.com", subject: "Cannot reset password", body: "Hello support team, I've tried resetting my password three times today. Each time I click the link in the email it says the link has expired. I need to place an order for my business urgently. Please help." },
  { name: "Charlotte Wilson", email: "charlotte.w@gmail.com", subject: "Double charged on my card", body: "Hi, I just noticed I was charged twice for the same order (#66789). My bank statement shows two identical charges of $89.99 from your store yesterday. Please refund the duplicate charge as soon as possible." },
  { name: "Benjamin Taylor", email: "b.taylor@company.com", subject: "Unexpected charge on my account", body: "Hello, I cancelled my subscription last month but I was still charged $49.99 this month. I have the cancellation confirmation email. Please refund this charge and confirm my subscription is cancelled." },
  { name: "Ava Thomas", email: "ava.thomas@hotmail.com", subject: "I need an invoice for my order", body: "Hi, I placed an order last month for business purposes and I need an official invoice with VAT for my accountant. Order number is #12987. Can you send this to my email as a PDF? Thank you." },
  { name: "William Jackson", email: "w.jackson@gmail.com", subject: "Very bad customer service", body: "I am extremely frustrated. I've sent 4 emails over the past week and nobody has replied. This is completely unacceptable. I have a simple question about my order and I can't get any help. I am considering disputing the charge with my bank." },
  { name: "Chloe White", email: "chloe.white@email.com", subject: "Product quality is terrible", body: "The product I received looks nothing like the photos on your website. The quality is very poor and the material is different from what was described. I feel completely misled by the product listing. I want a full refund and I will be leaving a negative review." },
  { name: "Alexander Harris", email: "alex.h@gmail.com", subject: "Third time this has happened", body: "This is the third order in a row where something has gone wrong. Last time the wrong item, before that a damaged product, and now my package has been lost. I am a loyal customer but this is making me want to shop elsewhere. Please make this right." },
  { name: "Grace Clark", email: "grace.clark@gmail.com", subject: "Question about your return policy", body: "Hi, I want to buy a gift for my mother but I'm not sure about your return policy. If the size is wrong, can she return it? What is the time limit? Does she need the receipt or is the order number enough?" },
  { name: "Henry Lewis", email: "henry.l@outlook.com", subject: "Do you offer discounts for bulk orders?", body: "Hello, I run a small business and I'm interested in ordering your products in bulk (around 50 units). Do you offer any business discounts or wholesale pricing? I'd love to discuss this further." },
  { name: "Lily Robinson", email: "lily.r@gmail.com", subject: "Is my size available?", body: "Hi, I've been trying to order the Classic Hoodie in size XS for a week but it keeps showing as out of stock. Do you know when it will be back? Is there a way to get notified? I really want this item." },
  { name: "Sebastian Scott", email: "seb.scott@gmail.com", subject: "How long does delivery take?", body: "Hello, I need to order a gift for a friend's birthday next Friday. Is standard delivery fast enough or should I pay for express? I'm based in London. Also, can you gift wrap it?" },
  { name: "Zoe Young", email: "zoe.young@email.com", subject: "Promo code not working", body: "Hi, I have a promo code SAVE20 that I received in an email last week but it's not working at checkout. It says \"invalid code\" but the email says it's valid until end of month. Can you help? I'm trying to place an order right now." },
];

export const FIRST_NAMES = ["Emma", "Liam", "Olivia", "Noah", "Ava", "William", "Sophia", "James", "Isabella", "Oliver", "Charlotte", "Benjamin", "Amelia", "Elijah", "Mia", "Lucas", "Harper", "Mason", "Evelyn", "Logan", "Luna", "Ethan", "Chloe", "Aiden", "Penelope", "Jackson", "Layla", "Sebastian", "Riley", "Mateo", "Zoey", "Jack", "Nora", "Owen", "Lily", "Theodore", "Eleanor", "Henry", "Hannah", "Samuel", "Lillian", "Alexander", "Addison", "Daniel", "Aubrey", "Michael", "Ellie"];
export const LAST_NAMES = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson"];
export const DOMAINS = ["gmail.com", "hotmail.com", "yahoo.com", "outlook.com", "icloud.com", "email.com", "me.com"];
